import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo } from "next/font/google";

import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

// Geist (للإنجليزي / الكود)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Cairo (للعربي)
const cairo = Cairo({
    subsets: ["arabic"],
    weight: ["300", "400", "500", "600", "700"],
    display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                           params,
                                         }: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
      <html lang={locale} dir={dir}>
      <body
          className={`${cairo.className} antialiased`}
      >
      <NextIntlClientProvider messages={messages}>
            {children}
      </NextIntlClientProvider>
      </body>
      </html>
  );
}
